[package]
name = "choki"
version = "0.0.1"
edition = "2021"
description="A simple http server from scratch."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"